spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cyci?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: kr.soft.study.dto   # DTO 위치
  configuration:
    map-underscore-to-camel-case: true           # user_id → userId 자동 매핑